
-- Conteúdo inicial público do Studiorium.

insert into public.templates (id,title,slug,category,doc_type,style,description,downloads,featured,sections) values ('tpl-banner-sustentabilidade','Banner Científico — Sustentabilidade','banner-cientifico-sustentabilidade','Faculdade','Banner científico','Clássico','Modelo para mostras científicas, projetos de iniciação científica e congressos estudantis.',1240,true,'["Introdução", "Objetivos", "Metodologia", "Resultados", "Conclusão", "Referências"]'::jsonb) on conflict (id) do nothing;
insert into public.templates (id,title,slug,category,doc_type,style,description,downloads,featured,sections) values ('tpl-tcc-classica','Estrutura de TCC — Caderno Clássico','estrutura-tcc-caderno-classico','Faculdade','Trabalho acadêmico','Dark academia','Estrutura para introdução, referencial teórico, metodologia, resultados, conclusão e referências.',3210,true,'["Resumo", "Introdução", "Referencial teórico", "Metodologia", "Resultados", "Conclusão", "Referências"]'::jsonb) on conflict (id) do nothing;
insert into public.templates (id,title,slug,category,doc_type,style,description,downloads,featured,sections) values ('tpl-feira-ciencias','Projeto para Feira de Ciências','projeto-feira-de-ciencias','Escola','Projeto científico','Escolar','Modelo guiado para problema, hipótese, experimento, registro de resultados e apresentação.',890,true,'["Problema", "Hipótese", "Materiais", "Procedimento", "Resultados", "Conclusão"]'::jsonb) on conflict (id) do nothing;
insert into public.templates (id,title,slug,category,doc_type,style,description,downloads,featured,sections) values ('tpl-artigo-abnt','Artigo Científico — Estrutura ABNT','artigo-cientifico-estrutura-abnt','Pesquisa','Artigo','Acadêmico','Organização de artigo com resumo, palavras-chave, seções principais e referências.',2715,false,'["Resumo", "Palavras-chave", "Introdução", "Método", "Resultados", "Discussão", "Referências"]'::jsonb) on conflict (id) do nothing;
insert into public.templates (id,title,slug,category,doc_type,style,description,downloads,featured,sections) values ('tpl-seminario-humanas','Seminário de Humanidades','seminario-de-humanidades','Escola','Apresentação','Editorial','Roteiro de apresentação para história, sociologia, filosofia, literatura e áreas afins.',670,false,'["Contexto", "Questão central", "Argumentos", "Fontes", "Síntese"]'::jsonb) on conflict (id) do nothing;
insert into public.templates (id,title,slug,category,doc_type,style,description,downloads,featured,sections) values ('tpl-resumo-expandido','Resumo Expandido para Mostra Científica','resumo-expandido-mostra-cientifica','Pesquisa','Resumo expandido','Científico','Estrutura concisa para submissão em mostras, feiras e encontros acadêmicos.',1428,false,'["Introdução", "Objetivos", "Metodologia", "Resultados", "Conclusão", "Referências"]'::jsonb) on conflict (id) do nothing;
insert into public.profiles (user_id,username,display_name,bio,profile_type,is_public,created_at) values ('seed_nucleo','nucleo-studiorium','Núcleo Studiorium','Curadoria editorial de materiais introdutórios, metodologia e integridade acadêmica.','instituicao',true,'2026-08-01T10:00:00.000Z') on conflict (user_id) do nothing;
insert into public.profiles (user_id,username,display_name,bio,profile_type,is_public,created_at) values ('seed_helena','helena-monte','Helena Monte','Professora e pesquisadora interessada em educação científica e aprendizagem baseada em projetos.','professor',true,'2026-08-03T10:00:00.000Z') on conflict (user_id) do nothing;
insert into public.profiles (user_id,username,display_name,bio,profile_type,is_public,created_at) values ('seed_lucas','lucas-alencar','Lucas Alencar','Universitário, autor de projetos de iniciação científica e materiais de organização de estudos.','universitario',true,'2026-08-05T10:00:00.000Z') on conflict (user_id) do nothing;
insert into public.publications (id,owner_id,author_name,title,slug,abstract,content,area,level,keywords,license,status,views,downloads,created_at,published_at) values ('pub-educacao-ia','seed_nucleo','Núcleo Studiorium','Uso responsável de inteligência artificial em atividades escolares','uso-responsavel-ia-atividades-escolares','Um guia introdutório sobre autoria, verificação de fontes e uso responsável de ferramentas de inteligência artificial no estudo.','Ferramentas de inteligência artificial podem apoiar planejamento, revisão e exploração de ideias, mas o estudante continua responsável por compreender o conteúdo, conferir informações, declarar usos relevantes e preservar a própria autoria. Referências devem ser verificadas na fonte original antes da entrega.','Educação','Ensino médio',ARRAY['educação','IA','autoria']::text[],'CC BY-NC 4.0','published',418,87,'2026-08-12T14:00:00.000Z','2026-08-12T14:00:00.000Z') on conflict (id) do nothing;
insert into public.publications (id,owner_id,author_name,title,slug,abstract,content,area,level,keywords,license,status,views,downloads,created_at,published_at) values ('pub-metodologia','seed_nucleo','Núcleo Studiorium','Como transformar uma pergunta em problema de pesquisa','pergunta-em-problema-de-pesquisa','Notas práticas para delimitar tema, problema, hipótese e objetivos sem perder clareza metodológica.','Um problema de pesquisa útil é específico o bastante para orientar a investigação e aberto o bastante para exigir análise. Delimite público, contexto, período e variável principal; depois verifique se os dados necessários são acessíveis e se a pergunta cabe no tempo disponível.','Metodologia','Graduação',ARRAY['metodologia','pesquisa','TCC']::text[],'CC BY-NC 4.0','published',731,192,'2026-08-10T10:30:00.000Z','2026-08-10T10:30:00.000Z') on conflict (id) do nothing;
insert into public.publications (id,owner_id,author_name,title,slug,abstract,content,area,level,keywords,license,status,views,downloads,created_at,published_at) values ('pub-feira-ciencias','seed_helena','Helena Monte','Aprendizagem baseada em projetos em feiras de ciências escolares','aprendizagem-projetos-feiras-ciencias','Síntese de práticas para transformar feiras de ciências em processos de investigação, registro, comunicação e revisão de hipóteses.','Uma feira de ciências ganha valor formativo quando o projeto começa com uma pergunta investigável, registra tentativas e erros e termina com comunicação dos resultados. O foco não deve estar apenas no produto final, mas no percurso documentado pelo estudante.','Educação científica','Ensino fundamental',ARRAY['feira de ciências','projetos','aprendizagem']::text[],'CC BY 4.0','published',302,64,'2026-08-08T09:20:00.000Z','2026-08-08T09:20:00.000Z') on conflict (id) do nothing;
insert into public.discussions (id,author_id,author_name,title,body,category,status,created_at) values ('disc-ia-ensino','seed_nucleo','Núcleo Studiorium','A inteligência artificial pode melhorar o ensino?','Discussão aberta sobre usos responsáveis de IA em sala de aula, sem substituir autoria, leitura crítica e verificação de fontes.','Tecnologia','published','2026-08-16T18:15:00.000Z') on conflict (id) do nothing;
insert into public.discussions (id,author_id,author_name,title,body,category,status,created_at) values ('disc-tcc-dois-meses','seed_lucas','Lucas Alencar','Como estruturar a metodologia de um TCC em dois meses?','Troca de experiências sobre cronogramas realistas, definição de escopo, coleta de dados e escrita progressiva.','Metodologia','published','2026-08-15T11:00:00.000Z') on conflict (id) do nothing;
insert into public.discussions (id,author_id,author_name,title,body,category,status,created_at) values ('disc-feira-ciencias','seed_helena','Helena Monte','O que torna uma feira de ciências realmente investigativa?','Quais critérios ajudam a diferenciar um experimento demonstrativo de um projeto em que o estudante realmente formula, testa e revisa uma hipótese?','Educação','published','2026-08-14T16:40:00.000Z') on conflict (id) do nothing;
insert into public.replies (id,discussion_id,author_id,author_name,body,status,created_at) values ('reply-seed-1','disc-ia-ensino','seed_helena','Helena Monte','Um bom ponto de partida é declarar quando a ferramenta foi usada e conferir cada referência antes de entregar o trabalho.','published','2026-08-16T19:00:00.000Z') on conflict (id) do nothing;
insert into public.replies (id,discussion_id,author_id,author_name,body,status,created_at) values ('reply-seed-2','disc-tcc-dois-meses','seed_nucleo','Núcleo Studiorium','Com prazo curto, vale reduzir o escopo, definir uma pergunta central e escrever a metodologia ao mesmo tempo em que a coleta é organizada.','published','2026-08-15T13:20:00.000Z') on conflict (id) do nothing;

-- Configurações públicas editáveis pelo painel ADM.
insert into public.site_settings (key,value) values ('site_title','"Studiorium"'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('hero_title','"Conhecimento que deixa vestígios."'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('hero_text','"Crie trabalhos, encontre modelos, publique descobertas e participe de conversas acadêmicas em um espaço que valoriza autoria, rigor e repertório."'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('site_notice','""'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('registrations_open','true'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('maintenance_mode','false'::jsonb) on conflict (key) do nothing;
