-- Studiorium v2.4 — Segurança de autenticação e auditoria

create table if not exists public.auth_rate_limits (
  key text primary key,
  scope text not null,
  attempts integer not null default 0 check (attempts >= 0),
  window_started_at timestamptz not null default now(),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);
create index if not exists auth_rate_limits_updated_idx on public.auth_rate_limits(updated_at);
create index if not exists auth_rate_limits_blocked_idx on public.auth_rate_limits(blocked_until) where blocked_until is not null;

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  event text not null,
  user_id text,
  email_hash text,
  ip_hash text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists security_events_created_idx on public.security_events(created_at desc);
create index if not exists security_events_event_idx on public.security_events(event, created_at desc);
create index if not exists security_events_user_idx on public.security_events(user_id, created_at desc) where user_id is not null;

alter table public.auth_rate_limits enable row level security;
alter table public.security_events enable row level security;

grant all on table public.auth_rate_limits, public.security_events to service_role;
grant usage, select on all sequences in schema public to service_role;
