-- Studiorium v2.2 — upgrade do painel administrativo para projetos v2.1 já existentes.
-- Execute UMA vez no SQL Editor do Supabase se o schema da v2.1 já foi criado.

alter table public.users add column if not exists status text not null default 'active';
alter table public.users add column if not exists suspension_reason text not null default '';
alter table public.users add column if not exists suspended_at timestamptz;
alter table public.publications add column if not exists featured boolean not null default false;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'users_status_check') then
    alter table public.users add constraint users_status_check check (status in ('active','suspended'));
  end if;
end $$;

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id text not null,
  action text not null,
  target_type text not null default 'system',
  target_id text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_created_idx on public.admin_audit_log(created_at desc);

alter table public.site_settings enable row level security;
alter table public.admin_audit_log enable row level security;
grant all on table public.site_settings, public.admin_audit_log to service_role;

insert into public.site_settings (key,value) values ('site_title','"Studiorium"'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('hero_title','"Conhecimento que deixa vestígios."'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('hero_text','"Crie trabalhos, encontre modelos, publique descobertas e participe de conversas acadêmicas em um espaço que valoriza autoria, rigor e repertório."'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('site_notice','""'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('registrations_open','true'::jsonb) on conflict (key) do nothing;
insert into public.site_settings (key,value) values ('maintenance_mode','false'::jsonb) on conflict (key) do nothing;
